### ISSUE TITLE
[BUG] I'm getting the error "ImageMagick binary cannot be found at"

### ISSUE THREAD

**Issue by nguyenxuantan27112000** [FujiwaraChoki/MoneyPrinter#117]
![Screenshot 2024-02-09 163647](https://github.com/FujiwaraChoki/MoneyPrinter/assets/100926854/31fa4a9e-f270-4982-8785-b9e25b9132bc)

**Comment by nguyenxuantan27112000** [comment]
I have already assigned the path. So what is the problem I'm facing, everyone?
![2](https://github.com/FujiwaraChoki/MoneyPrinter/assets/100926854/7bf414fa-07a0-471c-9a4d-03fcc83cfb33)

**Comment by mschmidt291** [comment]
Set the env variable `IMAGEMAGICK_BINARY` to the full magick.exe path. Should solve the problem.

**Comment by synergy6060** [comment]
hi

**Comment by nguyenxuantan27112000** [comment]
![3](https://github.com/FujiwaraChoki/MoneyPrinter/assets/100926854/78e4af76-c2b7-4e68-a486-00a07c1a51ae)
Do you mean to do that? I did and it still doesn't work

> Set the env variable `IMAGEMAGICK_BINARY` to the full magick.exe path. Should solve the problem.

**Comment by tobiaserich** [comment]
No, use the .env file in the main folder.

**Comment by nguyenxuantan27112000** [comment]
![4](https://github.com/FujiwaraChoki/MoneyPrinter/assets/100926854/3af7d607-f643-49d3-9fee-2673e1210f8f)
I did that but it still doesn't work

> No, use the .env file in the main folder.

**Comment by tobiaserich** [comment]
rename it to .env or change the .env directly.
Currently you are working with the .env.example

**Comment by RicardoMonteiroSimoes** [comment]
And refresh that api key, everybody knows it now :)
